### ISSUE TITLE
The "completed_tasks" command does not work

### ISSUE THREAD

**Issue by ckrybus** [bcongdon/todoist-to-sqlite#1]
Hi,

thanks for the awesome software, very clean code :+1: 

I noticed this line in your code:

```python
def completed_tasks(db_path, auth):
    ...
    if num_items == 0 or True:  # this evaluates always to True, the completed items are not being downloaded
        break
```

To me it looks like some kind of temporary debugging change which got committed by accident ...

**Comment by bcongdon** [comment]
Whoops! Thanks for the report. This should be fixed with v0.2 https://github.com/bcongdon/todoist-to-sqlite/releases/tag/v0.2
